### ISSUE TITLE
Body isnt it making it through to a controller

### ISSUE THREAD

**Issue by claridgicus** [rdlabo/serverless-nestjs#3]
https://gitlab.com/claridgicus/nest-serverless-body-issue/tree/master

@Body() body - Isn't making it through to serverless when its deployed and fires off an error on offline mode 

```
TypeError: Map#toJSON isn't generic
    at String.toJSON (C:\Users\Claridgicus\AppData\Roaming\npm\node_modules\serverless\node_modules\core-js\modules\_collection-to-json.js:6:38)
    at Function.<anonymous> (C:\Users\Claridgicus\AppData\Roaming\npm\node_modules\serverless\node_modules\core-js\modules\_ctx.js:18:15)
    at JSON.stringify (<anonymous>)
    at Function.stringify [as default] (C:\Users\Claridgicus\code\serverless-nestjs-master\node_modules\fast-safe-stringify\index.js:11:18)
    at ModuleTokenFactory.getDynamicMetadataToken (C:\Users\Claridgicus\code\serverless-nestjs-master\node_modules\@nestjs\core\injector\module-token-factory.js:20:69)
    at ModuleTokenFactory.create (C:\Users\Claridgicus\code\serverless-nestjs-master\node_modules\@nestjs\core\injector\module-token-factory.js:12:27)
    at ModuleCompiler.compile (C:\Users\Claridgicus\code\serverless-nestjs-master\node_modules\@nestjs\core\injector\compiler.js:19:47)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 1: std::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >::vector<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> >
 2: v8::internal::wasm::SignatureMap::Find
 3: v8::internal::Builtins::CallableFor
 4: v8::internal::Builtins::CallableFor
 5: v8::internal::Builtins::CallableFor
 6: 000002C66E8043C1
```

**Comment by claridgicus** [comment]
npm i
sls offline 

Hit an end point
watch it go 💥

**Comment by rdlabo** [comment]
In my environment, this is work well. 

```
  @Get('test')
  async blob(@Body() body: any) {
    return body;
  }
```

When start dev-server using `npm start` ( or `npm start:dev` ), your repository is work well?
