### ISSUE TITLE
sls offline throwing a bunch of type errors

### ISSUE THREAD

**Issue by michaelbats** [rdlabo/serverless-nestjs#6]
I've tried to deploy a test app several times, looked at the blogpost and thorugh nestjs's github issues around this and so far no luck, currently stuck at this: 

```
λ sls offline
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
PATH/test-app/node_modules/@nestjs/core/nest-application.d.ts (40,9): A rest parameter must be of an array type.
PATH/test-app/node_modules/@nestjs/core/nest-application.d.ts (40,24): JSDoc types can only be used inside documentation comments.
PATH/test-app/node_modules/@types/jest/index.d.ts (39,31): A rest parameter must be of an array type.
PATH/test-app/node_modules/@types/jest/index.d.ts (124,54): A rest parameter must be of an array type.
PATH/test-app/node_modules/@types/jest/index.d.ts (218,113): A tuple type element list cannot be empty.
PATH/test-app/node_modules/@types/jest/index.d.ts (220,145): Type 'ArgsType<T[M]>' does not satisfy the constraint 'any[]'.
  Type '{}' is not assignable to type 'any[]'.
    Property 'length' is missing in type '{}'.
PATH/test-app/node_modules/@types/jest/index.d.ts (785,14): A rest parameter must be of an array type.
PATH/test-app/node_modules/@types/jest/index.d.ts (786,10): A rest parameter must be of an array type.
PATH/test-app/node_modules/@types/jest/index.d.ts (803,51): Type 'ArgsType<T[P]>' does not satisfy the constraint 'any[]'.
  Type '{}' is not assignable to type 'any[]'.
PATH/test-app/node_modules/@types/jest/index.d.ts (850,34): A rest parameter must be of an array type.
PATH/test-app/node_modules/@types/jest/index.d.ts (866,37): A rest parameter must be of an array type.
PATH/test-app/node_modules/@types/superagent/index.d.ts (16,1): Invalid 'reference' directive syntax.
Unhandled rejection Error: EPERM: operation not permitted, symlink 'PATH\test-app\package.json' -> 'PATH\test-app\.build\package.json'    at Object.symlinkSync (fs.js:904:3)
    at TypeScriptPlugin.<anonymous> (PATH\test-app\node_modules\@hewmen\serverless-plugin-typescript\src\index.ts:146:10)
    at Generator.next (<anonymous>)
    at PATH\test-app\node_modules\@hewmen\serverless-plugin-typescript\dist\src\index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (PATH\test-app\node_modules\@hewmen\serverless-plugin-typescript\dist\src\index.js:3:12)
    at TypeScriptPlugin.copyExtras (PATH\test-app\node_modules\@hewmen\serverless-plugin-typescript\dist\src\index.js:121:16)
    at TypeScriptPlugin.<anonymous> (PATH\test-app\node_modules\@hewmen\serverless-plugin-typescript\src\index.ts:133:16)
    at Generator.next (<anonymous>)
    at fulfilled (PATH\test-app\node_modules\@hewmen\serverless-plugin-typescript\dist\src\index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by rdlabo** [comment]
related: https://github.com/rdlabo/serverless-nestjs/issues/7
